# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - mongo
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    command: npm run dev
    volumes:
      - .:/app/
  mongo:
    image: mongo:4.0-xenial
    ports:
      - '27017:27017'
